name: Run Pethon Hello
on:
  push:
    branches: [ "main" ]
jobs:
    my_build_job:
      runs-on: ubuntu-latest
      steps:
          - name: Install Python
            run: sudo apt update && sudo apt install -y python3
          - name: Check out the repository to the runner
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'
          - name: Run python script Hello.py
            run: python3 scripts/Hello.py
